Replacing `customize_icons` with more generalized `customize` task
This task is also constructed exactly the same as `update` and
`configure`.

diff --git a/dots b/dots
--- a/dots
+++ b/dots
@@ -207,21 +207,50 @@ EOM
   fi
 }
 
-# ------------------------------------------------------------- customize_icons
+# ------------------------------------------------------------------- customize
 
-desc customize_icons <<EOM
-Usage: $_me customize_icons
+desc customize <<EOM
+Usage: $_me customize [--all] [customization_script]
 
-Customize icons of Homebrew-installed applications.
+Run the specified package update script.
 
-For more information, reference the following script:
-  $DOTFILES/script/customizations/customize_icons.rb
+customization scripts can be added to:
+  $DOTFILES/script/customizations/
 EOM
-customize_icons() {
-  echo ">> Customizing icons of Homebrew-installed applications..."
-  $DOTFILES/script/customizations/customize_icons.rb
+_run_customization_script() {
+  if [[ -e "$1" ]]; then
+    echo ">> Running $(basename $1)"
+    $1
+  else
+    echo "Error: customization script '$1' not found." && exit 1
+  fi
 }
+customize() {
+  customizations_dir=$DOTFILES/script/customizations
+  script_file=$customizations_dir/$1
+  if [[ -n "$1" ]]; then
+    if [[ "$1" == "--all" ]]; then
+      for f in $customizations_dir/*
+      do
+        _run_customization_script $f
+      done
+    elif [[ "$1" == "list" ]]; then
+      for f in $customizations_dir/*
+      do
+        echo $(basename "$f")
+      done
+    else
+      _run_customization_script $script_file
+    fi
+  else
+    cat <<EOM
+Customization script must be specified. You can see available scripts by running
 
+$_me customize list
+EOM
+    exit 1
+  fi
+}
 
 # ------------------------------------------------------------------- configure
 
