Expand _debug() and add _die()

diff --git a/dots b/dots
--- a/dots
+++ b/dots
@@ -145,13 +145,54 @@ fi
 # intended to be used before a printf statement.
 #
 # Usage:
-#   _debug printf "Debug info"
+#   _debug printf "Debug info. Variable: %s\n" "$0"
 _debug() {
   if [[ "${_use_debug:-"0"}" -eq 1 ]]; then
+    # Prefix debug message with "bug (U+1F41B)"
     printf "🐛  "
     "$@"
     printf "――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――\n"
   fi
+}
+# debug()
+#
+# Uses the more familiar syntax and echo so printf can be avoided if desired.
+# I prefer printf, personally, since it's more explicit, but I acknowledge that
+# it's more cumbersome.
+#
+# Usage:
+#   debug "Debug info. Variable: $0"
+debug() {
+  _debug echo "$@"
+}
+
+###############################################################################
+# Die
+###############################################################################
+
+# _die()
+#
+# Simple function for exiting with an error after executing the specified
+# command.
+#
+# Usage:
+#   _die printf "Error message. Variable: %s\n" "$0"
+_die() {
+  # Prefix die message with "cross mark (U+274C)", often displayed as a red x.
+  printf "❌  "
+  "$@" 1>&2
+  exit 1
+}
+# die()
+#
+# Uses the more familiar syntax and echo so printf can be avoided if desired.
+# I prefer printf, personally, since it's more explicit, but I acknowledge that
+# it's more cumbersome.
+#
+# Usage:
+#   die "Error message. Variable: $0"
+die() {
+  _die echo "$@"
 }
 
 ###############################################################################
