Adding a couple missing `printf` newlines and replacing another `echo`

diff --git a/dots b/dots
--- a/dots
+++ b/dots
@@ -46,7 +46,7 @@ _me=$(basename "$0")
 
 # Ensure that $DOTFILES is set in the environment.
 if [[ -z $DOTFILES ]]; then
-  printf "\$DOTFILES must be set to your dotfiles directory" && exit 1
+  printf "\$DOTFILES must be set to your dotfiles directory\n" && exit 1
 fi
 
 # $source_dir
@@ -109,7 +109,7 @@ done
 # To make the description text available to other functions, desc() assigns the
 # text to a variable with the format $_desc_function_name
 desc() {
-  [[ -z $1 ]] && printf "desc: No task name specified." && exit 1
+  [[ -z $1 ]] && printf "desc: No task name specified.\n" && exit 1
   if [[ -n $2 ]]; then
     read -d '' "_desc_$1" <<EOM
 $2
@@ -150,11 +150,11 @@ _run_script() {
     printf ">> Running %s\n" "$(basename "$1")"
     $1
   else
-    printf "'%s' not found." "$1" && exit 1
+    printf "'%s' not found.\n" "$1" && exit 1
   fi
 }
 _runner() {
-  [[ -z $1 ]] && echo "_runner: No subdirectory specified." && exit 1
+  [[ -z $1 ]] && printf "_runner: No subdirectory specified.\n" && exit 1
   subdir=$1
   subdir_path=$DOTFILES/script/$subdir
   script_file=$subdir_path/$2
