Tweaking help text. In particular, removing 'Error' throughout.
These aren't really being treated as 'Errors,' so it's a bit of a
misnomer. Removing these instances and simplifying help output.

diff --git a/dots b/dots
--- a/dots
+++ b/dots
@@ -46,7 +46,7 @@ _me=$(basename $0)
 
 # Ensure that $DOTFILES is set in the environment.
 if [[ -z $DOTFILES ]]; then
-  echo "Error: \$DOTFILES must be set to your dotfiles directory" && exit 1
+  echo "\$DOTFILES must be set to your dotfiles directory" && exit 1
 fi
 
 # $source_dir
@@ -115,7 +115,7 @@ _run_script() {
     echo ">> Running $(basename $1)"
     $1
   else
-    echo "Error: script '$1' not found." && exit 1
+    echo "'$1' not found." && exit 1
   fi
 }
 _runner() {
@@ -357,17 +357,17 @@ Add the specified dotfile to the dotfiles repository and link.
 EOM
 add() {
   if [[ $# = 0 ]]; then
-    echo "Error: must specify a valid file or directory name." && exit 1
+    echo "Must specify a valid file or directory name." && exit 1
   elif [[ ! -e $1 ]]; then
-    echo "Error: file or directory does not exist." && exit 1
+    echo "File or directory does not exist." && exit 1
   else
     filename=$(basename $1)
     target_file=$target_dir/$filename
     source_file=$source_dir/$filename
     if [[ ! -e $source_file ]]; then
-      echo "file does not exist"
+      echo "File does not exist."
     elif [[ ! -L $target_file ]]; then
-      echo "file is not a symlink"
+      echo "File is not a symlink."
     else
       mv $target_file $source_dir
       echo "Linking $source_file => $target_file"
@@ -385,17 +385,17 @@ Unlink the specified file and move from the dotfiles repository back to $HOME"
 EOM
 restore() {
   if [[ $# = 0 ]]; then
-    echo "Error: must specify a valid file or directory name." && exit 1
+    echo "Must specify a valid file or directory name." && exit 1
   elif [[ ! -e $1 ]]; then
-    echo "Error: file or directory does not exist." && exit 1
+    echo "File or directory does not exist." && exit 1
   else
     filename=$(basename $1)
     target_file=$target_dir/$filename
     source_file=$source_dir/$filename
     if [[ ! -e $source_file ]]; then
-      echo "file does not exist"
+      echo "File does not exist."
     elif [[ ! -L $target_file ]]; then
-      echo "file is not a symlink"
+      echo "File is not a symlink."
     else
       rm $target_file
       mv $source_file $target_file
@@ -589,7 +589,7 @@ _dotfiles_main() {
     eval $@
     exit 0
   else
-    echo "Error: task not found."
+    echo "Task not found."
     exit 1
   fi
 }
