Adding `--all` option to `dots update`
`--all` runs all of the package install scripts in the packages
directory.

In order to make this work nicely, creating a new
`_run_package_update_script` function for running each individual
package update script.

diff --git a/dots b/dots
--- a/dots
+++ b/dots
@@ -165,7 +165,7 @@ update_submodules() {
 # ---------------------------------------------------------------------- update
 
 desc update <<EOM
-Usage: $_me update [list] [package_script]
+Usage: $_me update [list] [--all] [package_script]
 
 Run the specified package update script.
 
@@ -173,25 +173,37 @@ package scripts can be added to:
   $DOTFILES/script/packages/
 
 EOM
+_run_package_update_script() {
+  if [[ -a "$1" ]]; then
+    echo ">> Running $(basename $1)"
+    $1
+  else
+    echo "Error: package update script '$1' not found." && exit 1
+  fi
+}
 update() {
   packages_dir=$DOTFILES/script/packages
   script_file=$packages_dir/$1
   if [[ -n "$1" ]]; then
-    if [[ "$1" == "list" ]]; then
+    if [[ "$1" == "--all" ]]; then
+      for f in $packages_dir/*
+      do
+        _run_package_update_script $f
+      done
+    elif [[ "$1" == "list" ]]; then
       for f in $packages_dir/*
       do
         echo $(basename "$f")
       done
-    elif [[ -a "$script_file" ]]; then
-      echo ">> Running $(basename $script_file)"
-      $script_file
     else
-      echo "Error: package update script not found." && exit 1
+      _run_package_update_script $script_file
     fi
   else
-    echo "Update script must be specified. You can see available scripts by running
+    cat <<EOM
+Update script must be specified. You can see available scripts by running
 
 $_me update list" && exit 1
+EOM
   fi
 }
 
